extends: default
rules:
  braces: disable
  brackets: disable
  colons: disable
  comments-indentation: disable
  line-length: { max: 240 }
  document-start: disable
  truthy: { check-keys: false }
  comments: { min-spaces-from-content: 1 }
  indentation: { spaces: 2, indent-sequences: consistent }
