-- zkCEX auth + KYC persistence (PostgreSQL backend).
-- Mirror of sqlite.sql with SQL-standard equivalents:
--   AUTOINCREMENT       -> GENERATED BY DEFAULT AS IDENTITY
--   BLOB                -> BYTEA
--   INTEGER (32-bit)    -> BIGINT for unix-second timestamps so 2038 is not
--                          a footgun on the production-track backend.
-- Idempotent: CREATE ... IF NOT EXISTS everywhere.

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email TEXT UNIQUE NOT NULL,
  pw_hash BYTEA NOT NULL,
  pw_salt BYTEA NOT NULL,
  name TEXT NOT NULL,
  opex_user TEXT NOT NULL,
  kyc_status TEXT NOT NULL DEFAULT 'none',
  kyc_verified_at BIGINT,
  kyc_name TEXT,
  kyc_phone TEXT,
  kyc_birth TEXT,
  kyc_gender TEXT,
  kyc_carrier TEXT,
  created_at BIGINT NOT NULL,
  kyc_provider_request_id TEXT
);

CREATE TABLE IF NOT EXISTS sessions (
  token TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS kyc_verifications (
  id TEXT PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  code TEXT NOT NULL,
  expires_at BIGINT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  carrier TEXT,
  name TEXT,
  rrn_front TEXT,
  rrn_back1 TEXT,
  phone TEXT,
  created_at BIGINT NOT NULL,
  sms_provider_message_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_kyc_verifications_user ON kyc_verifications(user_id);

CREATE TABLE IF NOT EXISTS sumsub_applicants (
  external_user_id TEXT PRIMARY KEY,
  applicant_id TEXT NOT NULL,
  level_name TEXT NOT NULL,
  created_at BIGINT NOT NULL,
  last_status TEXT,
  last_review_answer TEXT,
  last_synced_at BIGINT
);

CREATE TABLE IF NOT EXISTS sumsub_webhooks (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  applicant_id TEXT NOT NULL,
  type TEXT,
  body_json TEXT,
  received_at BIGINT NOT NULL,
  signature_valid INTEGER NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sumsub_applicants_aid ON sumsub_applicants(applicant_id);
CREATE INDEX IF NOT EXISTS idx_sumsub_webhooks_aid ON sumsub_webhooks(applicant_id);

CREATE TABLE IF NOT EXISTS geo_decisions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  ts BIGINT NOT NULL,
  ip_redacted TEXT NOT NULL,
  country TEXT,
  endpoint TEXT NOT NULL,
  decision TEXT NOT NULL,
  reason TEXT
);
CREATE INDEX IF NOT EXISTS idx_geo_decisions_ts ON geo_decisions(ts);

-- WebAuthn / passkey credentials. Mirror of the SQLite shape.
CREATE TABLE IF NOT EXISTS webauthn_credentials (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  credential_id TEXT NOT NULL UNIQUE,
  public_key_cose_b64 TEXT NOT NULL,
  sign_count BIGINT NOT NULL DEFAULT 0,
  attestation_type TEXT,
  aaguid TEXT,
  transports TEXT,
  device_name TEXT,
  created_at BIGINT NOT NULL,
  last_used_at BIGINT
);
CREATE INDEX IF NOT EXISTS idx_webauthn_user ON webauthn_credentials(user_id);

CREATE TABLE IF NOT EXISTS webauthn_challenges (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  challenge_b64 TEXT NOT NULL UNIQUE,
  purpose TEXT NOT NULL,
  user_id BIGINT,
  email TEXT,
  created_at BIGINT NOT NULL,
  expires_at BIGINT NOT NULL,
  used INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_webauthn_challenges_expires ON webauthn_challenges(expires_at);
