{{- range $name, $cfg := .Values.services }}
{{- if $cfg.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/part-of: zkcex
automountServiceAccountToken: {{ default false $cfg.singleton }}
---
{{- end }}
{{- end }}
