package co.nilin.opex.api.ports.binance.controller

import co.nilin.opex.common.OpexError
import co.nilin.opex.common.utils.LoggerDelegate
import com.fasterxml.jackson.databind.JsonNode
import kotlinx.coroutines.reactive.awaitSingle
import org.springframework.beans.factory.annotation.Value
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.reactive.function.client.WebClientResponseException
import org.springframework.web.reactive.function.client.bodyToMono
import java.security.Principal

/**
 * Exposes the authenticated user's Proof-of-Liabilities inclusion proof. The actual proof is
 * generated by the external pol-snapshot-server, which holds the per-epoch Merkle-sum tree and the
 * user's per-epoch nonce. We forward the authenticated principal's UUID as the `user_id` so a user
 * can only fetch their own proof; the server-side `epoch_nonce` never reaches the client.
 */
@RestController
@RequestMapping("/v3/pol")
class PolController(private val webClientBuilder: WebClient.Builder) {

    private val logger by LoggerDelegate()

    @Value("\${app.pol.url:}")
    private lateinit var baseUrl: String

    private val webClient: WebClient by lazy { webClientBuilder.build() }

    @GetMapping("/inclusion-proof", produces = [MediaType.APPLICATION_JSON_VALUE])
    suspend fun inclusionProof(
        principal: Principal,
        @RequestParam(required = false) epoch: Long?,
    ): JsonNode {
        ensureConfigured()
        val userId = principal.name
        val targetEpoch = epoch ?: latestEpoch()
        logger.info("fetching PoL inclusion proof for user=$userId epoch=$targetEpoch")
        return fetchJson("$baseUrl/api/v1/audit/user-proof?epoch=$targetEpoch&user_id=$userId")
    }

    @GetMapping("/certificate/latest", produces = [MediaType.APPLICATION_JSON_VALUE])
    suspend fun latestCertificate(): JsonNode {
        ensureConfigured()
        return fetchJson("$baseUrl/api/v1/certificate/latest")
    }

    @GetMapping("/certificate/pubkey", produces = [MediaType.APPLICATION_JSON_VALUE])
    suspend fun signingPubkey(): JsonNode {
        ensureConfigured()
        return fetchJson("$baseUrl/api/v1/certificate/pubkey")
    }

    private suspend fun latestEpoch(): Long {
        val resp = fetchJson("$baseUrl/api/v1/certificate/latest")
        return resp.path("certificate").path("epoch").asLong()
    }

    /**
     * Run a GET against the snapshot server and translate its failures into clean OpexError
     * responses. Without this, a 404 from the snapshot server (e.g., epoch not yet ingested)
     * leaks as a Spring 500 to the user; a connection error becomes an even messier stack
     * trace. We map upstream 4xx/5xx onto stable Binance-API-style error codes.
     */
    private suspend fun fetchJson(uri: String): JsonNode {
        return try {
            webClient.get()
                .uri(uri)
                .accept(MediaType.APPLICATION_JSON)
                .retrieve()
                .onStatus({ it.isError }, { it.createException() })
                .bodyToMono<JsonNode>()
                .awaitSingle()
        } catch (e: WebClientResponseException) {
            logger.warn("pol-snapshot-server returned ${e.statusCode} for $uri: ${e.responseBodyAsString.take(200)}")
            throw when (val status = e.statusCode) {
                HttpStatus.NOT_FOUND -> OpexError.NoRecordFound.exception()
                HttpStatus.BAD_REQUEST -> OpexError.BadRequest.exception()
                HttpStatus.UNAUTHORIZED -> OpexError.UnAuthorized.exception()
                HttpStatus.FORBIDDEN -> OpexError.Forbidden.exception()
                else -> if (status.is5xxServerError) {
                    OpexError.ServiceUnavailable.exception()
                } else {
                    OpexError.InternalServerError.exception()
                }
            }
        } catch (e: Exception) {
            // Connection refused / timeout / DNS / etc. — the snapshot server is unreachable.
            logger.warn("pol-snapshot-server unreachable while calling $uri: ${e.message}")
            throw OpexError.ServiceUnavailable.exception()
        }
    }

    private fun ensureConfigured() {
        if (baseUrl.isBlank()) {
            logger.warn("app.pol.url is not configured; /v3/pol/* endpoints cannot serve")
            throw OpexError.ServiceUnavailable.exception()
        }
    }
}
