package co.nilin.opex.api.ports.binance.controller

import co.nilin.opex.common.utils.LoggerDelegate
import com.fasterxml.jackson.databind.JsonNode
import kotlinx.coroutines.reactive.awaitSingle
import org.springframework.beans.factory.annotation.Value
import org.springframework.http.MediaType
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RequestParam
import org.springframework.web.bind.annotation.RestController
import org.springframework.web.reactive.function.client.WebClient
import org.springframework.web.reactive.function.client.bodyToMono
import java.security.Principal

/**
 * Exposes the authenticated user's Proof-of-Liabilities inclusion proof. The actual proof is
 * generated by the external pol-snapshot-server, which holds the per-epoch Merkle-sum tree and the
 * user's per-epoch nonce. We forward the authenticated principal's UUID as the `user_id` so a user
 * can only fetch their own proof; the server-side `epoch_nonce` never reaches the client.
 */
@RestController
@RequestMapping("/v3/pol")
class PolController(private val webClientBuilder: WebClient.Builder) {

    private val logger by LoggerDelegate()

    @Value("\${app.pol.url:}")
    private lateinit var baseUrl: String

    private val webClient: WebClient by lazy { webClientBuilder.build() }

    @GetMapping("/inclusion-proof", produces = [MediaType.APPLICATION_JSON_VALUE])
    suspend fun inclusionProof(
        principal: Principal,
        @RequestParam(required = false) epoch: Long?,
    ): JsonNode {
        require(baseUrl.isNotBlank()) { "app.pol.url must be configured" }
        val userId = principal.name
        val targetEpoch = epoch ?: latestEpoch()
        logger.info("fetching PoL inclusion proof for user=$userId epoch=$targetEpoch")
        return webClient.get()
            .uri("$baseUrl/api/v1/audit/user-proof?epoch=$targetEpoch&user_id=$userId")
            .accept(MediaType.APPLICATION_JSON)
            .retrieve()
            .onStatus({ it.isError }, { it.createException() })
            .bodyToMono<JsonNode>()
            .awaitSingle()
    }

    @GetMapping("/certificate/latest", produces = [MediaType.APPLICATION_JSON_VALUE])
    suspend fun latestCertificate(): JsonNode {
        require(baseUrl.isNotBlank()) { "app.pol.url must be configured" }
        return webClient.get()
            .uri("$baseUrl/api/v1/certificate/latest")
            .accept(MediaType.APPLICATION_JSON)
            .retrieve()
            .onStatus({ it.isError }, { it.createException() })
            .bodyToMono<JsonNode>()
            .awaitSingle()
    }

    @GetMapping("/certificate/pubkey", produces = [MediaType.APPLICATION_JSON_VALUE])
    suspend fun signingPubkey(): JsonNode {
        require(baseUrl.isNotBlank()) { "app.pol.url must be configured" }
        return webClient.get()
            .uri("$baseUrl/api/v1/certificate/pubkey")
            .accept(MediaType.APPLICATION_JSON)
            .retrieve()
            .onStatus({ it.isError }, { it.createException() })
            .bodyToMono<JsonNode>()
            .awaitSingle()
    }

    private suspend fun latestEpoch(): Long {
        val resp = webClient.get()
            .uri("$baseUrl/api/v1/certificate/latest")
            .accept(MediaType.APPLICATION_JSON)
            .retrieve()
            .onStatus({ it.isError }, { it.createException() })
            .bodyToMono<JsonNode>()
            .awaitSingle()
        return resp.path("certificate").path("epoch").asLong()
    }
}
