#!/usr/bin/env python3
"""End-to-end failover test for the two-region Postgres cluster.

Workflow:
  1. Write 1000 rows on the primary (:5434).
  2. Wait for replication to catch up; verify replica (:5435) has all 1000.
  3. Trigger failover.sh — stops primary, promotes replica.
  4. Write 100 more rows on the (formerly replica) new primary at :5435.
  5. Verify the new rows are present.
  6. Report RTO (recovery time objective) and RPO (recovery point objective).
  7. Drop the test table on the new primary, whatever happened.

Uses pg8000 only — already a dependency of auth_server, no new pip installs.
"""
from __future__ import annotations

import os
import subprocess
import sys
import time
import traceback

import pg8000.dbapi as pg

HERE = os.path.dirname(os.path.abspath(__file__))
PRIMARY_DSN = dict(host="127.0.0.1", port=5434, database="zkcex_auth",
                   user="app", password="app-password")
REPLICA_DSN = dict(host="127.0.0.1", port=5435, database="zkcex_auth",
                   user="app", password="app-password")

TEST_TABLE = "failover_test_rows"


def connect(dsn, retries=30, delay=0.5):
    """Connect with retries — Postgres may briefly refuse during promotion."""
    last = None
    for _ in range(retries):
        try:
            return pg.connect(**dsn)
        except Exception as e:
            last = e
            time.sleep(delay)
    raise RuntimeError(f"could not connect to {dsn['host']}:{dsn['port']}: {last}")


def now_ms() -> float:
    return time.monotonic() * 1000.0


def drop_test_table_anywhere() -> None:
    """Best-effort cleanup against whichever node is currently writable."""
    for dsn in (PRIMARY_DSN, REPLICA_DSN):
        try:
            conn = pg.connect(**dsn)
        except Exception:
            continue
        try:
            cur = conn.cursor()
            cur.execute("SELECT pg_is_in_recovery()")
            in_recovery = cur.fetchone()[0]
            if not in_recovery:
                cur.execute(f"DROP TABLE IF EXISTS {TEST_TABLE}")
                conn.commit()
        except Exception:
            pass
        finally:
            try:
                conn.close()
            except Exception:
                pass


def main() -> int:
    print("==== zkCEX Postgres failover end-to-end test ====")

    # ---- Phase 0: setup table on primary ----
    print("[setup] connecting to primary :5434")
    pconn = connect(PRIMARY_DSN)
    pcur = pconn.cursor()
    pcur.execute(f"DROP TABLE IF EXISTS {TEST_TABLE}")
    pcur.execute(f"""
        CREATE TABLE {TEST_TABLE} (
            id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            payload TEXT NOT NULL,
            written_at_ms DOUBLE PRECISION NOT NULL,
            phase TEXT NOT NULL
        )
    """)
    pconn.commit()

    # ---- Phase 1: write 1000 rows on primary ----
    t0 = now_ms()
    for i in range(1000):
        pcur.execute(
            f"INSERT INTO {TEST_TABLE} (payload, written_at_ms, phase) VALUES (%s, %s, %s)",
            (f"row-{i:04d}", now_ms(), "pre-failover"),
        )
    pconn.commit()
    write_ms = now_ms() - t0
    print(f"[primary] 1000 rows written in {write_ms:.0f} ms")

    # capture primary LSN at the moment of last commit
    pcur.execute("SELECT pg_current_wal_lsn()")
    primary_commit_lsn = pcur.fetchone()[0]
    commit_time = now_ms()

    # ---- Phase 2: wait for replica to catch up ----
    rconn = connect(REPLICA_DSN)
    rcur = rconn.cursor()
    catchup_deadline = time.time() + 30
    replica_visible_at = None
    while time.time() < catchup_deadline:
        rcur.execute(f"SELECT COUNT(*) FROM {TEST_TABLE}")
        n = rcur.fetchone()[0]
        if n == 1000:
            replica_visible_at = now_ms()
            break
        time.sleep(0.02)
    if replica_visible_at is None:
        print(f"[replica] FAILED to see 1000 rows within 30s (saw {n})")
        return 2
    catchup_ms = replica_visible_at - commit_time
    print(f"[replica] 1000 rows visible {catchup_ms:.0f} ms after primary commit")

    # Final lag snapshot before we kill the primary
    pcur.execute("""
        SELECT pg_wal_lsn_diff(pg_current_wal_lsn(), replay_lsn)
        FROM pg_stat_replication LIMIT 1
    """)
    replay_lag_bytes = pcur.fetchone()
    replay_lag_bytes = replay_lag_bytes[0] if replay_lag_bytes else None
    print(f"[replica] replay_lag_bytes at handoff = {replay_lag_bytes}")

    try:
        pconn.close()
    except Exception:
        pass
    try:
        rconn.close()
    except Exception:
        pass

    # ---- Phase 3: trigger failover ----
    print("[failover] running failover.sh")
    fo_start = now_ms()
    fo = subprocess.run(
        ["bash", os.path.join(HERE, "failover.sh")],
        capture_output=True, text=True,
    )
    sys.stdout.write(fo.stdout)
    sys.stderr.write(fo.stderr)
    if fo.returncode != 0:
        print(f"[failover] failover.sh exited {fo.returncode}")
        return 3

    # Confirm the replica is now out of recovery and writable
    new_primary = connect(REPLICA_DSN)
    npcur = new_primary.cursor()
    promoted_at = None
    for _ in range(120):
        npcur.execute("SELECT pg_is_in_recovery()")
        if npcur.fetchone()[0] is False:
            promoted_at = now_ms()
            break
        time.sleep(0.1)
    if promoted_at is None:
        print("[failover] new primary still in recovery after 12s")
        return 4
    rto_ms = promoted_at - fo_start
    print(f"[failover] promotion completed in {rto_ms/1000:.2f} s")

    # ---- Phase 4: write 100 rows on new primary ----
    t0 = now_ms()
    for i in range(100):
        npcur.execute(
            f"INSERT INTO {TEST_TABLE} (payload, written_at_ms, phase) VALUES (%s, %s, %s)",
            (f"post-{i:03d}", now_ms(), "post-failover"),
        )
    new_primary.commit()
    new_write_ms = now_ms() - t0
    print(f"[new-primary] 100 rows written in {new_write_ms:.0f} ms")

    # ---- Phase 5: verify ----
    npcur.execute(f"SELECT COUNT(*) FROM {TEST_TABLE}")
    total = npcur.fetchone()[0]
    npcur.execute(f"SELECT COUNT(*) FROM {TEST_TABLE} WHERE phase='post-failover'")
    post = npcur.fetchone()[0]
    npcur.execute(f"SELECT COUNT(*) FROM {TEST_TABLE} WHERE phase='pre-failover'")
    pre = npcur.fetchone()[0]
    print(f"[verify] total={total} pre-failover={pre} post-failover={post}")

    pre_ok = (pre == 1000)
    post_ok = (post == 100)

    # ---- Phase 6: report ----
    print("")
    print("==== RESULTS ====")
    rpo_bytes = replay_lag_bytes if replay_lag_bytes is not None else 0
    rpo_pass = pre_ok and (rpo_bytes == 0)
    rto_pass = rto_ms <= 30 * 60 * 1000  # 30 min target
    post_pass = post_ok

    print(f"RTO: {rto_ms/1000:.2f} s (target: 30 min) -- {'PASS' if rto_pass else 'FAIL'}")
    print(f"RPO: {rpo_bytes} bytes lost (synchronous_commit='on' would give 0) -- {'PASS' if rpo_pass else 'FAIL'}")
    print(f"Post-failover writes: {post} of 100 -- {'PASS' if post_pass else 'FAIL'}")

    try:
        new_primary.close()
    except Exception:
        pass

    return 0 if (rto_pass and rpo_pass and post_pass) else 5


if __name__ == "__main__":
    rc = 99
    try:
        rc = main()
    except Exception:
        traceback.print_exc()
        rc = 1
    finally:
        drop_test_table_anywhere()
    sys.exit(rc)
