"""One-time bootstrap for the threshold-custody demo.

  python3 -m tools.custody.bootstrap --threshold 3 --total 5

What this does:

  1. Materialise a custodial private key.
       - DEFAULT (recommended for the demo): read the existing custodial
         private key from tools/hardhat-sim/.local/deployment.json. This
         keeps the on-chain custodial address identical to what hardhat
         already has funded, so withdrawals continue to work end-to-end.
       - If `--fresh` is passed, generate a new random secp256k1 key. The
         resulting address will not have any hardhat balance and you'll
         have to fund it yourself.

  2. Shamir-split the 32-byte private key into TOTAL shares with the given
     THRESHOLD. Each share is written to:
         tools/.local/custody/shard_<i>.bin    (33 bytes: index || payload)

  3. Generate per-node bearer tokens (independent for each node) and a
     coordinator token. Tokens are written into a `.tokens.env` file inside
     tools/.local/custody/ for the launch script to source.

  4. Write public.json (custodial address + threshold/total + node URLs).

  5. Write launch.sh — a shell script that runs the 5 signer nodes and the
     coordinator with the right env in the background.

  6. **Best-effort wipe** the in-memory key.

Critical: bootstrap NEVER prints the private key, never logs it, never
writes it as plaintext anywhere on disk. The only persisted artefact is
the per-share encoded bytes (one share alone reveals nothing about the key
under Shamir's scheme).
"""

from __future__ import annotations

import argparse
import json
import os
import secrets
import stat
import sys
import time

if __package__ in (None, ""):
    HERE = os.path.dirname(os.path.abspath(__file__))
    PARENT = os.path.dirname(HERE)
    if PARENT not in sys.path:
        sys.path.insert(0, PARENT)
    from custody import ethsign as _ethsign  # type: ignore
    from custody import shamir as _shamir  # type: ignore
else:
    from . import ethsign as _ethsign
    from . import shamir as _shamir


def _hardhat_deployment_path() -> str:
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", "hardhat-sim", ".local", "deployment.json"))


def _local_dir() -> str:
    here = os.path.dirname(os.path.abspath(__file__))
    return os.path.normpath(os.path.join(here, "..", ".local", "custody"))


def _zero_bytearray(b: bytearray) -> None:
    for i in range(len(b)):
        b[i] = 0


def _materialise_key(fresh: bool) -> bytearray:
    """Return the custodial private key as a mutable bytearray.

    Caller is responsible for zeroing it after use.
    """
    if fresh:
        # Pick a random 32-byte scalar in [1, N-1].
        while True:
            cand = bytearray(secrets.token_bytes(32))
            x = int.from_bytes(cand, "big")
            if 1 <= x < _shamir.N:
                return cand
            _zero_bytearray(cand)
    # Default: lift from deployment.json so the address matches the chain.
    path = _hardhat_deployment_path()
    if not os.path.exists(path):
        print(
            f"ERROR: {path} not found; either deploy hardhat first or rerun with --fresh",
            file=sys.stderr,
        )
        sys.exit(2)
    with open(path) as f:
        d = json.load(f)
    pk_hex = (d.get("deployerPrivKey") or "").strip()
    if pk_hex.startswith("0x") or pk_hex.startswith("0X"):
        pk_hex = pk_hex[2:]
    if len(pk_hex) != 64:
        print("ERROR: deployment.json deployerPrivKey is malformed", file=sys.stderr)
        sys.exit(2)
    return bytearray(bytes.fromhex(pk_hex))


def _write_share(path: str, idx: int, payload: bytes) -> None:
    if not (1 <= idx <= 255):
        raise ValueError("share index must fit in one byte (1..255)")
    if len(payload) != 32:
        raise ValueError("share payload must be 32 bytes")
    with open(path, "wb") as f:
        f.write(bytes([idx]) + payload)
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)  # 0600


def _write_tokens_env(
    path: str,
    *,
    coordinator_token: str,
    node_tokens: list[str],
    node_ports: list[int],
    coordinator_port: int,
) -> None:
    lines = [
        "# Generated by tools/custody/bootstrap.py — DO NOT COMMIT",
        f"export CUSTODY_COORDINATOR_TOKEN='{coordinator_token}'",
        f"export CUSTODY_COORDINATOR_PORT={coordinator_port}",
    ]
    urls = [f"http://127.0.0.1:{p}" for p in node_ports]
    lines.append(f"export CUSTODY_NODE_URLS='{','.join(urls)}'")
    lines.append(f"export CUSTODY_NODE_TOKENS='{','.join(node_tokens)}'")
    for i, t in enumerate(node_tokens):
        lines.append(f"export CUSTODY_NODE_TOKEN_{i}='{t}'")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)


def _write_launch(
    path: str,
    *,
    here: str,
    public_json_path: str,
    shard_paths: list[str],
    node_ports: list[int],
    coordinator_port: int,
    threshold: int,
    total: int,
) -> None:
    """Write a launch.sh that spins up signer nodes + coordinator."""
    repo_root = os.path.normpath(os.path.join(here, "..", ".."))
    tokens_env = os.path.join(os.path.dirname(public_json_path), ".tokens.env")
    log_dir = os.path.join(os.path.dirname(public_json_path), "logs")
    lines = [
        "#!/usr/bin/env bash",
        "# Launch the demo threshold-custody fleet:",
        f"#   {len(shard_paths)} signer nodes on ports {','.join(str(p) for p in node_ports)}",
        f"#   1 coordinator on port {coordinator_port} (m-of-n {threshold}-of-{total})",
        "set -euo pipefail",
        f"cd {repo_root}",
        f"source {tokens_env}",
        f"mkdir -p {log_dir}",
        "",
        "# Kill any previous run.",
        f"for p in {' '.join(str(p) for p in node_ports)} {coordinator_port}; do",
        "  pid=$(lsof -ti tcp:$p || true)",
        '  if [ -n "$pid" ]; then echo "[custody] killing pid $pid on :$p"; kill $pid || true; fi',
        "done",
        "sleep 0.4",
        "",
        "# Spawn signer nodes.",
    ]
    for i, (port, shard) in enumerate(zip(node_ports, shard_paths, strict=False)):
        node_token_var = f"CUSTODY_NODE_TOKEN_{i}"
        lines.append(
            f'CUSTODY_NODE_TOKEN="${{{node_token_var}}}" \\\n'
            f"  python3 -m tools.custody.signer_node \\\n"
            f"    --port {port} --node-id n{i} \\\n"
            f"    --share-path {shard} \\\n"
            f"    > {log_dir}/signer_n{i}.log 2>&1 &"
        )
        lines.append(f'echo "[custody] signer n{i} started on :{port} (pid $!)"')
    lines.append("")
    lines.append("# Give signer nodes a moment to bind sockets.")
    lines.append("sleep 0.6")
    lines.append("")
    lines.append("# Spawn coordinator.")
    lines.append(
        f"python3 -m tools.custody.coordinator \\\n"
        f"  --port {coordinator_port} \\\n"
        f"  --threshold {threshold} --total {total} \\\n"
        f"  --public-json {public_json_path} \\\n"
        f'  --coordinator-token "$CUSTODY_COORDINATOR_TOKEN" \\\n'
        f"  > {log_dir}/coordinator.log 2>&1 &"
    )
    lines.append(f'echo "[custody] coordinator started on :{coordinator_port} (pid $!)"')
    lines.append("")
    lines.append('echo ""')
    lines.append('echo "[custody] all started. health:"')
    lines.append("sleep 0.8")
    lines.append(f"curl -sS http://127.0.0.1:{coordinator_port}/health || true")
    lines.append('echo ""')
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    os.chmod(path, 0o700)


def main() -> None:
    ap = argparse.ArgumentParser(description="zkCEX custody bootstrap")
    ap.add_argument("--threshold", type=int, default=3)
    ap.add_argument("--total", type=int, default=5)
    ap.add_argument(
        "--fresh",
        action="store_true",
        help="generate a new random key instead of reading deployment.json",
    )
    ap.add_argument("--coordinator-port", type=int, default=5530)
    ap.add_argument("--node-port-base", type=int, default=5520)
    args = ap.parse_args()

    if not (2 <= args.threshold <= args.total <= 31):
        print("ERROR: must have 2 <= threshold <= total <= 31", file=sys.stderr)
        sys.exit(2)

    here = os.path.dirname(os.path.abspath(__file__))
    out_dir = _local_dir()
    os.makedirs(out_dir, exist_ok=True)
    os.chmod(out_dir, stat.S_IRWXU)  # 0700

    # 1. Materialise key (mutable bytearray we will zero).
    key_buf = _materialise_key(args.fresh)
    try:
        # 2. Derive address (without printing the priv key anywhere).
        addr = _ethsign.privkey_to_address(bytes(key_buf))

        # 3. Shamir-split.
        shares = _shamir.split(bytes(key_buf), n=args.total, threshold=args.threshold)

        # 4. Write shares.
        shard_paths = []
        for idx, payload in shares:
            sp = os.path.join(out_dir, f"shard_{idx - 1}.bin")
            _write_share(sp, idx, payload)
            shard_paths.append(sp)

        # 5. Generate tokens.
        coordinator_token = secrets.token_urlsafe(32)
        node_tokens = [secrets.token_urlsafe(32) for _ in range(args.total)]
        node_ports = [args.node_port_base + i for i in range(args.total)]

        # 6. public.json — pinned address + topology.
        public_json_path = os.path.join(out_dir, "public.json")
        public = {
            "address": addr,
            "threshold": args.threshold,
            "total": args.total,
            "coordinator_url": f"http://127.0.0.1:{args.coordinator_port}",
            "nodes": [
                {"node_id": f"n{i}", "url": f"http://127.0.0.1:{p}", "share_index": i + 1}
                for i, p in enumerate(node_ports)
            ],
            "created_at": int(time.time()),
            "scheme": "shamir-secp256k1-reconstruct-then-sign",
            "scheme_warning": (
                "DEMO ONLY: not real threshold ECDSA. The custodial private key "
                "is briefly reconstructed in coordinator memory at signing time "
                "and zeroed after broadcast. Production deployments must use "
                "HSMs (CloudHSM/YubiHSM) or threshold-ECDSA MPC services."
            ),
        }
        with open(public_json_path, "w") as f:
            json.dump(public, f, indent=2)
        os.chmod(public_json_path, stat.S_IRUSR | stat.S_IWUSR | stat.S_IRGRP | stat.S_IROTH)

        # 7. tokens env.
        tokens_env = os.path.join(out_dir, ".tokens.env")
        _write_tokens_env(
            tokens_env,
            coordinator_token=coordinator_token,
            node_tokens=node_tokens,
            node_ports=node_ports,
            coordinator_port=args.coordinator_port,
        )

        # 8. launch.sh.
        launch = os.path.join(out_dir, "launch.sh")
        _write_launch(
            launch,
            here=here,
            public_json_path=public_json_path,
            shard_paths=shard_paths,
            node_ports=node_ports,
            coordinator_port=args.coordinator_port,
            threshold=args.threshold,
            total=args.total,
        )

        # 9. Print operator-facing summary. NEVER prints the priv key.
        print("zkCEX threshold-custody bootstrap complete.")
        print(f"  custodial address : {addr}")
        print(f"  m-of-n            : {args.threshold}-of-{args.total}")
        print("  shards            :")
        for p in shard_paths:
            print(f"      {p}")
        print(f"  public.json       : {public_json_path}")
        print(f"  tokens env        : {tokens_env}  (do not commit)")
        print(f"  launch script     : {launch}")
        print()
        print("Next:")
        print(f"  bash {launch}")
        print(
            f"  curl -s http://127.0.0.1:{args.coordinator_port}/health " "| python3 -m json.tool"
        )
        print()
        print("To wire chain_server, source the tokens env first:")
        print(f"  source {tokens_env}")
        print(
            f"  CUSTODY_COORDINATOR_URL=http://127.0.0.1:{args.coordinator_port} "
            "python3 tools/chain_server.py 5502"
        )
    finally:
        _zero_bytearray(key_buf)
        del key_buf


if __name__ == "__main__":
    main()
